# Generated by Django 5.0.4 on 2024-05-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='city',
        ),
    ]
