# Generated by Django 5.0.4 on 2024-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_city_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
