# Generated by Django 5.0.4 on 2024-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customer_email_confirmed_remove_customer_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('treatment_type', models.CharField(choices=[('grooming', 'Grooming'), ('medical', 'Medical'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery')], max_length=20)),
                ('hospital', models.CharField(choices=[('hospital_a', 'Hospital A'), ('hospital_b', 'Hospital B'), ('hospital_c', 'Hospital C')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
