# Generated by Django 5.0.4 on 2024-06-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
    ]
