# Generated by Django 5.0.4 on 2024-07-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
