# Generated by Django 5.0.4 on 2024-07-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
