# Generated by Django 5.0.4 on 2024-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_name',
            field=models.CharField(default='Unknown vaccine', max_length=100),
            preserve_default=False,
        ),
    ]
