# Generated by Django 5.0.4 on 2024-08-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_appointment_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.petprofile'),
        ),
    ]
