# Generated by Django 5.0.4 on 2024-08-08 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_appointment_pet_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
