# Generated by Django 5.0.4 on 2024-08-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_prescription_pet_profile'),
        ('user', '0026_alter_appointment_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.hospital'),
        ),
    ]
