# Generated by Django 5.0.4 on 2024-07-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_notification_message_alter_notification_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
