# Generated by Django 5.0.4 on 2024-08-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_prescription_medicine_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
    ]
