# Generated by Django 5.0.4 on 2024-08-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_prescription_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.hospital'),
        ),
    ]
