# Generated by Django 5.0.4 on 2024-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_prescription_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(default='general clinic', max_length=255),
        ),
    ]
