# Generated by Django 5.0.4 on 2024-08-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_hospital_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='medicine',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
