# Generated by Django 5.0.4 on 2024-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(default='Unknown', max_length=255, null=True),
        ),
    ]
