# Generated by Django 5.0.4 on 2024-08-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_remove_medicine_instructions_and_more'),
        ('user', '0026_alter_appointment_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pet_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.petprofile'),
        ),
    ]
