# Generated by Django 5.0.4 on 2024-08-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_prescription_pet_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pet_profile',
        ),
    ]
